/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package travelsetia;

/**
 *
 * @author dimas
 */
public class MenuPesawat1 extends javax.swing.JPanel {

    /**
     * Creates new form MenuPesawat1
     */
    public MenuPesawat1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        iconPesawat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(53, 114, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 760, 310));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Pesawat");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 30));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 153, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Plus.png"))); // NOI18N
        jButton4.setText("Tambah");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 140, 50));

        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Change.png"))); // NOI18N
        jButton5.setText("Ubah");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 140, 50));

        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Minus.png"))); // NOI18N
        jButton6.setText("Hapus");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 140, 50));

        iconPesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Plane.png"))); // NOI18N
        add(iconPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Master Data > Pesawat");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 260, 30));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Harga");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 290, 50));

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Nama Pesawat");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, 50));

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Kota Keberangkatan");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, 50));

        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Destinasi");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 290, 50));

        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("Tanggal Keberangkatan");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 290, 50));

        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("Kursi Tersedia");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 290, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconPesawat;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
