/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package travelsetia;

import java.awt.Color;

/**
 *
 * @author dimas
 */
public class MenuPesawat1 extends javax.swing.JPanel {

    /**
     * Creates new form MenuPesawat1
     */
    public MenuPesawat1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        iconPesawat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaPesawatUp = new javax.swing.JTextField();
        tfKotaUp = new javax.swing.JTextField();
        tfDestinasiUp = new javax.swing.JTextField();
        tfTanggalUp = new javax.swing.JTextField();
        tfKursUp = new javax.swing.JTextField();
        tfHargaUp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(53, 114, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 760, 310));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Pesawat");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 30));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 153, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Plus.png"))); // NOI18N
        jButton4.setText("Tambah");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 140, 50));

        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Change.png"))); // NOI18N
        jButton5.setText("Ubah");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 140, 50));

        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Minus.png"))); // NOI18N
        jButton6.setText("Hapus");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(78, 25));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 140, 50));

        iconPesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Plane.png"))); // NOI18N
        add(iconPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Master Data > Pesawat");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 260, 30));

        tfNamaPesawatUp.setForeground(new java.awt.Color(153, 153, 153));
        tfNamaPesawatUp.setText("Nama Pesawat");
        tfNamaPesawatUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNamaPesawatUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNamaPesawatUpFocusLost(evt);
            }
        });
        tfNamaPesawatUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNamaPesawatUpKeyTyped(evt);
            }
        });
        add(tfNamaPesawatUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, 50));

        tfKotaUp.setForeground(new java.awt.Color(153, 153, 153));
        tfKotaUp.setText("Kota Keberangkatan");
        tfKotaUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKotaUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKotaUpFocusLost(evt);
            }
        });
        add(tfKotaUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, 50));

        tfDestinasiUp.setForeground(new java.awt.Color(153, 153, 153));
        tfDestinasiUp.setText("Destinasi");
        tfDestinasiUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDestinasiUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDestinasiUpFocusLost(evt);
            }
        });
        tfDestinasiUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDestinasiUpActionPerformed(evt);
            }
        });
        add(tfDestinasiUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 290, 50));

        tfTanggalUp.setForeground(new java.awt.Color(153, 153, 153));
        tfTanggalUp.setText("Tanggal Keberangkatan");
        tfTanggalUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTanggalUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTanggalUpFocusLost(evt);
            }
        });
        add(tfTanggalUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 290, 50));

        tfKursUp.setForeground(new java.awt.Color(153, 153, 153));
        tfKursUp.setText("Kursi Tersedia");
        tfKursUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKursUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKursUpFocusLost(evt);
            }
        });
        tfKursUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKursUpActionPerformed(evt);
            }
        });
        add(tfKursUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 290, 50));

        tfHargaUp.setForeground(new java.awt.Color(153, 153, 153));
        tfHargaUp.setText("Harga");
        tfHargaUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfHargaUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfHargaUpFocusLost(evt);
            }
        });
        add(tfHargaUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 290, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void tfKursUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKursUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKursUpActionPerformed

    private void tfNamaPesawatUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaPesawatUpKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfNamaPesawatUpKeyTyped

    private void tfDestinasiUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDestinasiUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDestinasiUpActionPerformed

    private void tfNamaPesawatUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNamaPesawatUpFocusGained
        // TODO add your handling code here:
        if(tfNamaPesawatUp.getText().equals("Nama Pesawat")){
            tfNamaPesawatUp.setText("");
            tfNamaPesawatUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfNamaPesawatUpFocusGained

    private void tfNamaPesawatUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNamaPesawatUpFocusLost
        // TODO add your handling code here:
        if(tfNamaPesawatUp.getText().equals("")){
            tfNamaPesawatUp.setText("Nama Pesawat");
            tfNamaPesawatUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfNamaPesawatUpFocusLost

    private void tfKotaUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaUpFocusGained
        // TODO add your handling code here:
        if(tfKotaUp.getText().equals("Kota Keberangkatan")){
            tfKotaUp.setText("");
            tfKotaUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfKotaUpFocusGained

    private void tfKotaUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaUpFocusLost
        // TODO add your handling code here:
        if(tfKotaUp.getText().equals("")){
            tfKotaUp.setText("Kota Keberangkata");
            tfKotaUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfKotaUpFocusLost

    private void tfDestinasiUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDestinasiUpFocusGained
        // TODO add your handling code here:
        if(tfDestinasiUp.getText().equals("Destinasi")){
            tfDestinasiUp.setText("");
            tfDestinasiUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfDestinasiUpFocusGained

    private void tfDestinasiUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDestinasiUpFocusLost
        // TODO add your handling code here:
        if(tfDestinasiUp.getText().equals("")){
            tfDestinasiUp.setText("Destinasi");
            tfDestinasiUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfDestinasiUpFocusLost

    private void tfTanggalUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTanggalUpFocusGained
        // TODO add your handling code here:
        if(tfTanggalUp.getText().equals("Tanggal Keberangkatan")){
            tfTanggalUp.setText("");
            tfTanggalUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfTanggalUpFocusGained

    private void tfTanggalUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTanggalUpFocusLost
        // TODO add your handling code here:
        if(tfTanggalUp.getText().equals("")){
            tfTanggalUp.setText("Tanggal Keberangkatan");
            tfTanggalUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfTanggalUpFocusLost

    private void tfKursUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKursUpFocusGained
        // TODO add your handling code here:
        if(tfKursUp.getText().equals("Kursi Tersedia")){
            tfKursUp.setText("");
            tfKursUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfKursUpFocusGained

    private void tfKursUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKursUpFocusLost
        // TODO add your handling code here:
        if(tfKursUp.getText().equals("")){
            tfKursUp.setText("Kursi Tersedia");
            tfKursUp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfKursUpFocusLost

    private void tfHargaUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfHargaUpFocusGained
        // TODO add your handling code here:
        if(tfHargaUp.getText().equals("Harga")){
            tfHargaUp.setText("");
            tfHargaUp.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfHargaUpFocusGained

    private void tfHargaUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfHargaUpFocusLost
        // TODO add your handling code here:
        if(tfHargaUp.getText().equals("")){
            tfHargaUp.setText("Harga");
            tfHargaUp.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfHargaUpFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconPesawat;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfDestinasiUp;
    private javax.swing.JTextField tfHargaUp;
    private javax.swing.JTextField tfKotaUp;
    private javax.swing.JTextField tfKursUp;
    private javax.swing.JTextField tfNamaPesawatUp;
    private javax.swing.JTextField tfTanggalUp;
    // End of variables declaration//GEN-END:variables
}
